set -g default-terminal "screen-256color"
set-option -g default-command bash

# prefix to ctrl-a
set -g prefix C-a
bind C-a send-prefix

# reload ~/.tmux.conf
bind r source-file ~/.tmux.conf

# enable vi mode
setw -g mode-keys vi

# Enable mouse support
set-option -g mouse on
bind m set-option -g mouse on
bind M set-option -g mouse off

# Start copy mode when scrolling up
bind -n WheelUpPane copy-mode -e

# Window style adjustments
set -g window-style 'fg=colour240'
set -g window-active-style 'fg=colour254'

# Status Bar Adjustments
set-option -g status-bg colour235 #base02
set-option -g status-fg yellow #yellow
set-option -g status-attr dim

set-window-option -g window-status-fg brightyellow #base0
set-window-option -g window-status-bg colour236
set-window-option -g window-status-attr dim

set-window-option -g window-status-current-fg brightgreen
set-window-option -g window-status-current-bg colour236
set-window-option -g window-status-current-attr bright

set -g status-left "#[fg=white]#S "
set -g status-right "#[fg=white] %d %b %Y %H:%M"


